---
output:
    pdf_document:
        latex_engine: xelatex
        template: './pandoc-templates/appendices.tex'
        keep_tex: false
---
<!-- Title page -->
\section*{}
\pagenumbering{gobble}
\begin{center}

\LARGE{\textbf{Appendix 1}}
\vspace{20mm}

\large{\textbf{Organizations supporting the application}}\\

\end{center}

\begin{enumerate}
    \item{International Society of Physical and Rehabilitation Medicine (ISPRM)}
    \item{World Federation of Societies of Anaesthesiology (WFSA)}
    \item{World Medical Association (WMA)}
    \item{National Chapters of the International Association for the Study of Pain}
        \begin{itemize}
            \item{American Pain Society}
            \item{Asociación Chilena para el Estudio del Dolor [Chile]}
            \item{Asociacion Dominicana para el Estudio y Tratamiento del Dolor y Cuidados Paliativos [Dominican Repuplic]}
            \item{Asociación Istmeña para el Estudio del Dolor [Panama]}
            \item{Australian Pain Society}
            \item{Bangladesh Society for Study of Pain}
            \item{Belgian Pain Society}
            \item{British Pain Society}
            \item{Chinese Association for the Study of Pain}
            \item{Croatian Pain Society}
            \item{Dutch Pain Society}
            \item{German Pain Society}
            \item{Hong Kong Pain Society}
            \item{Indian Society for Study of Pain}
            \item{Iranian Pain Society}
            \item{Irish Pain Society}
            \item{Lebanese Society for the Study of Pain} 
            \item{Lithuanian Pain Society}
            \item{Malaysian Association for the Study of Pain}
            \item{Österreichische Schmerzgesellschaft [Austria]}
            \item{Pain Society of the Philippines}
            \item{PainSA [South Africa]}
            \item{Professional Health Association – Pain Section, Kosovo}
            \item{Saudi Society of Pain Medicine}
            \item{Serbian Pain Association of Pain Research and Treatment}
            \item{Sociedad Española Del Dolor [Spain]}
            \item{Society for the Study of Pain, Nigeria}
            \item{Sri Lanka Association for the Study of Pain}
            \item{Thai Association for the Study of Pain}
        \end{itemize}
\end{enumerate}

<!-- body -->
\newpage
\pagenumbering{gobble}

\includepdf[pages=-]{./appendix-files/isprm.pdf}

\newpage
\pagenumbering{gobble}

\includepdf[pages=-]{./appendix-files/wfsa.pdf}

\newpage
\pagenumbering{gobble}

\includepdf[pages=-]{./appendix-files/wma.pdf}

\newpage
\pagenumbering{gobble}

\includepdf[pages=-]{./appendix-files/iasp.pdf}

<!-- Title page -->
\section*{}
\begin{center}

\LARGE{\textbf{Appendix 2}} \\
\vspace{20mm}

\large{\textbf{Description and bias assessment of studies included in GRADE assessment}} \\
\vspace{5mm}

\end{center}

\justify
\large{\textbf{Adapted from:} Moore RA, Wiffen PJ, Derry S, Toelle T, Rice ASC.
Gabapentin for chronic neuropathic pain and fibromyalgia in adults. \textit{Cochrane Database of Systematic Reviews} \textbf{4}: CD007938, 2014. DOI: \href{http://dx.doi.org/10.1002/14651858.CD007938.pub3}{10.1002/14651858.CD007938.pub3}}

<!-- body -->
\newpage
\pagenumbering{gobble}

\includepdf[page=-]{./appendix-files/cochrane-study-descriptions.pdf}

<!-- Title page -->
\section*{}
\begin{center}

\LARGE{\textbf{Appendix 3}} \\
\vspace{20mm}

\large{\textbf{Summary of outcomes of studies included in GRADE assessment}} \\
\vspace{5mm}

\end{center}

\justify
\large{\textbf{Adapted from:} Moore RA, Wiffen PJ, Derry S, Toelle T, Rice ASC.
Gabapentin for chronic neuropathic pain and fibromyalgia in adults. \textit{Cochrane Database of Systematic Reviews} \textbf{4}: CD007938, 2014. DOI: \href{http://dx.doi.org/10.1002/14651858.CD007938.pub3}{10.1002/14651858.CD007938.pub3}}

<!-- body -->
\newpage
\pagenumbering{gobble}

\includepdf[page=-]{./appendix-files/cochrane-study-outcomes.pdf}

<!-- Title page -->
\section*{}
\begin{center}

\LARGE{\textbf{Appendix 4}} \\
\vspace{20mm}

\large{Finnerup NB, Attal N, Haroutounian S, McNicol E, Baron R, Dworkin RH, Gilron I, Haanpää M, Hansson P, Jensen TS, Kamerman PR, Lund K, Moore A, Raja SN, Rice AS, Rowbotham M, Sena E, Siddall P, Smith BH, Wallace M}\\
\vspace{5mm}

\large{\textbf{Pharmacotherapy for neuropathic pain in adults:
a systematic review and meta-analysis}}\\
\vspace{5mm}

\large{\textit{Lancet Neurology} \textbf{14}:162-173, 2015}\\
\vspace{5mm}

\large{DOI: \href{https://dx.doi.org/10.1016/S1474-4422(14)70251-0}{10.1016/S1474-4422(14)70251-0}}
\vspace{30mm}

\textbf{Supplementary data}\\
All supplementary information for the systematic review and meta-analysis is available for download.\\
\vspace{3mm}
\href{https://dl.dropboxusercontent.com/u/11805474/neml/who-application-2016/finnerup2015-supp-data.pdf?dl=1}{\textit{Access online}}
\end{center}

<!-- body -->
\newpage
\pagenumbering{gobble}

\includepdf[pages=-]{./appendix-files/appendix-2-finnerup.pdf}

<!-- Title page -->
\section*{}
\begin{center}

\LARGE{\textbf{Appendix 5}} \\
\vspace{20mm}

\large{Kamerman PR, Wadley AL, Davis KD, Hietaharju A, Jain P, Kopf A, Meyer AC, Raja SN, Rice AS, Smith BH, Treede RD, Wiffen PJ}\\
\vspace{5mm}

\large{\textbf{World Health Organization essential medicines lists: where are the drugs to treat neuropathic pain?}}\\
\vspace{5mm}

\large{\textit{PAIN} \textbf{156}:793-797, 2015}\\
\vspace{5mm}

\large{DOI: \href{https://dx.doi.org/10.1097/01.j.pain.0000460356.94374.a1}{10.1097/01.j.pain.0000460356.94374.a1}}
\vspace{30mm}

\textbf{Supplementary data}\\
All supplementary information, including data and analysis scripts, are available in a public GitHub repository.\\
\vspace{3mm}
\href{https://github.com/kamermanpr/who-neml}{\textit{Access online}}

\end{center}

<!-- body -->
\newpage
\pagenumbering{gobble}

\includepdf[pages=-]{./appendix-files/appendix-3-kamerman.pdf}

<!-- Title page -->
\section*{}
\begin{center}

\LARGE{\textbf{Appendix 6}}
\vspace{20mm}

\LARGE{\textbf{NEURONTIN}}
\vspace{5mm}

\Large{\textbf{Full prescribing information}}
\vspace{10mm}

\large{\textit{Food and Drug Administration (FDA)}}\\
\vspace{5mm}

\large{\textit{United States of America}}\\
\vspace{10mm}

\large{\textbf{Updated:} September 2015; \textbf{Reference ID:} 3818812}\\
\vspace{5mm}

\large{\href{http://www.accessdata.fda.gov/drugsatfda_docs/label/2015/020235s060,020882s043,021129s042lbl.pdf}{\textit{Access online}}}

\end{center}

<!-- body -->
\newpage
\pagenumbering{gobble}

\includepdf[pages=-]{./appendix-files/fda.pdf}

<!-- Title page -->
\section*{}
\begin{center}

\LARGE{\textbf{Appendix 7}}
\vspace{20mm}

\LARGE{\textbf{NEURONTIN}}
\vspace{5mm}

\Large{\textbf{Summary of product information (ANNEX III)}}
\vspace{10mm}

\large{\textit{European Medicines Agency (EMA)}}\\
\vspace{5mm}

\large{\textit{European Union}}\\
\vspace{10mm}

\large{\textbf{Updated:} September 2006}\\
\vspace{5mm}

\large{\href{http://www.ema.europa.eu/docs/en_GB/document_library/Referrals_document/Neurontin_30/WC500009308.pdf}{\textit{Access online}}}

\end{center}

<!-- body -->
\newpage
\pagenumbering{gobble}

\includepdf[pages=-]{./appendix-files/ema.pdf}
