---
output:
    pdf_document:
        latex_engine: xelatex
        template: './pandoc-templates/summary.tex'
        keep_tex: false
bibliography: './bib/library.bib'
csl: './bib/vancouver.csl'
---

_**We are applying for the inclusion of gabapentin as an analgesic agent for the management of neuropathic pain (central and peripheral) in adults on the WHO Model List of Essential Medicines, and are seeking endorsement for this application from governmental and non-governmental organisations**_. 

Gabapentin has regulatory approval for the treatment of neuropathic pain in adults by several stringent regulatory bodies (e.g., FDA and EMA), and all recent evidence-based treatment guidelines recommend gabapentin as one of the first-line agents for the pharmacological management of neuropathic pain.

A recent systematic review estimated the prevalence of neuropathic pain in the general, adult population to be about 7 to 10%, equating to over 380 million prevalent cases of adults with neuropathic pain globally. And, in certain chronic diseases that already impose or are predicted to impose a high burden of disease in developing countries, such as HIV-AIDS, diabetes mellitus, leprosy, the prevalence of neuropathic pain can be more than three times the population prevalence. In addition, developing countries are disproportionally affected by acute traumatic injuries (e.g., conflict-related trauma, motor vehicle injuries) that may cause nerve damage. The consequences of having neuropathic pain, like other chronic pain conditions, is a significant decrease in health-related quality of life, and a significant increase in the burden placed on health resources. 

Neuropathic pain is difficult to treat, and requires specific classes of medication for its management. Evidence-based recommendations include: tricyclic antidepressants (TCAs), $\alpha 2 \delta$-calcium channel ligands (gabapentin and pregabalin), and serotonin and noradrenaline reuptake inhibitors (SNRIs, duloxetine and venlafaxine) as first-line agents. The number needed to treat (NNT) to achieve 50% pain relief relative to placebo for these effective medications ranges between 4 and 9 [amitriptyline: 4.3 (95% CI: 3.6 to 5.3), gabapentin 6.3 (95% CI: 5.0 to 8.3)], and failure to respond adequately to a initial monotherapy necessitates switching to another class of agent, or using combination therapy. Thus, management of neuropathic pain requires an adequate armamentarium of medications that have proven efficacy and may be used in combination. 

The WHO recently urged member states to ensure, _“the availability of essential medicines for the management of symptoms, including pain,”_ and _“[the] education and training of healthcare professionals, in order to ensure adequate responses to palliative care needs.”_. Yet for neuropathic pain, the WHO Model List of Essential Medicines fails on both accounts. The list is deficient in drugs with proven efficacy in treating neuropathic pain, and which are recommended as first- or second-line agents in the treatment of neuropathic pain. And, the WHO Model Formulary provides out-dated and erroneous guidance on appropriate medications to use for treating neuropathic pain. These deficiencies are echoed in the national essential medicines lists of developing and emerging countries. Indeed, the WHO Model List of Essential Medicines, which informs national formularies, only provides one first- or second-line treatment option with proven efficacy in the treatment of neuropathic pain: amitriptyline. Our recent analysis of national essential medicine lists identified that almost 70% of countries only had one class of first-line medication (rising to $>$ 90% in low-income countries). In almost all cases the single agent available was a TCA, typically amitriptyline. Of the other first-line medications, gabapentin was the most commonly listed (30% of lists). Given its proven efficacy, good cost-utility, and global availability, we are thus applying for inclusion of gabapentin as an additional treatment for neuropathic pain on the Model Essential Medicines List. Support from governmental and non-governmental bodies will strengthen the application. 

